### PR TITLE
Expand dynamic_filters functionality, remove deprecated content

### PR DESCRIPTION
**Pull request by juulSme**
Dynamic filtering now supports:
- filters map with string keys
- order_by on multiple fields
- filter types prefix_search, search, or_lists
- explicitly enabling or disabling limit, offset, order_by
- filters for fields of named bindings other than the main binding
- dynamically creating other named_bindings with a caller-provided function
- generating docs for the new filters & changed behaviour

### CODE REVIEW

**Review by TimPelgrim — APPROVED** [review]
Op het oog is het zeker prima, ik denk dat de lakmoesproef gaat zijn hoe het in de implementatie is maar daar komen we snel achter.

**Comment by juulSme** [comment]
I'm making this WIP until we've used it in a project for a little while (using a github-branch dependency in hex) to see how it works out in practice.

**Comment by ddaugher** [comment]
love the additions, what is the proper format for the URL query params in order to get 'order_by' to work?

**Review by LouisMT — APPROVED** [review]

**Review by TimPelgrim — APPROVED** [review]
Looks good

**Pull request merged**
